/*
* NLP Architect Jenkinsfile
*/

pipeline {
    agent {
        docker {
            image 'python:3.6'
            label 'metal-node'
        }
    }
    options {
        timestamps()
    }
    environment { 
        NLP_ARCHITECT_BE = 'CPU'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build environment') {
            steps {
                sh 'pip install -U setuptools pip'
                sh 'pip install nlp-architect'
                sh 'python3 -m venv .nlp_architect_env'
                sh """
                . .nlp_architect_env/bin/activate
                pip3 install -U pip setuptools h5py
                export NLP_ARCHITECT_BE=CPU
                pip3 install -r requirements.txt
                pip3 install -r dev-requirements.txt
                pip3 install -e .
                python -m spacy download en
                """
            }
        }
        stage('Validation') {
            parallel {
                stage('Tests') {
                    steps {
                        sh """
                        . .nlp_architect_env/bin/activate
                        export LC_ALL=en_US.UTF-8
                        export LANG=en_US.UTF-8
                        pytest ./tests -rs -vv --cov=nlp_architect --junit-xml=pytest_unit.xml
                        """
                    }
                    post {
                        always {
                            junit 'pytest_unit.xml'
                        }
                        failure {
                            script {
                                currentBuild.result = 'FAILURE'
                            }
                        }
                    }
                }
                stage('flake8') {
                    steps {
                        sh """
                        . .nlp_architect_env/bin/activate
                        ./scripts/check_flake.sh
                        """
                    }
                    post {
                        failure {
                            script {
                                currentBuild.result = 'FAILURE'
                            }
                        }
                    }
                }
                stage('pylint') {
                    steps {
                        sh """
                        . .nlp_architect_env/bin/activate
                        ./scripts/check_pylint.sh
                        """
                    }
                    post {
                        failure {
                            script {
                                currentBuild.result = 'FAILURE'
                            }
                        }
                    }
                }
            }
        }
    }
    post {
        aborted {
            script {
                currentBuild.result = 'FAILURE'
            }
        }
        failure {
            script {
                currentBuild.result = 'FAILURE'
            }
        }
        always {
            deleteDir()
        }
        cleanup {
            deleteDir()
        }
    }
}
